### ISSUE TITLE
Wire framing, Lo-fi and high fidelity design of Login pages.

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#10]
Description: Using the sketches agreed on during meeting, design the wire frames, low fidelity and high fidelity of Login pages

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned to: Jesse philip zubairu

**Comment by jessexxzee** [comment]
ok,done

**Comment by jessexxzee** [comment]
https://www.figma.com/file/OKE18aXZ9ui2o6Db5QWJgB/TEAM-110-(Copy)-(Copy)?node-id=1189%3A22320
https://www.figma.com/file/OKE18aXZ9ui2o6Db5QWJgB/TEAM-110-(Copy)-(Copy)?node-id=111%3A925
https://www.figma.com/file/OKE18aXZ9ui2o6Db5QWJgB/TEAM-110-(Copy)-(Copy)?node-id=1385%3A58976
https://www.figma.com/file/OKE18aXZ9ui2o6Db5QWJgB/TEAM-110-(Copy)-(Copy)?node-id=1385%3A62835
https://www.figma.com/file/OKE18aXZ9ui2o6Db5QWJgB/TEAM-110-(Copy)-(Copy)?node-id=1383%3A30259
https://www.figma.com/file/OKE18aXZ9ui2o6Db5QWJgB/TEAM-110-(Copy)-(Copy)?node-id=1242%3A22775
