### ISSUE TITLE
Wire framing and Lo-fi design for landing and community pages

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#11]
Description: Using the sketches as agreed upon by the team during the meeting, design wire frames and low fidelity for both landing and community pages

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned to: Iruoma Valerie

**Comment by iruomavalerie** [comment]
Wiframes of community page has been developed
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1240%3A21441

**Comment by iruomavalerie** [comment]
Wireframe of landing page has been developed
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=358%3A1952

**Comment by iruomavalerie** [comment]
Low fidelity of community page has been adapted from from wireframes
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A30490

**Comment by iruomavalerie** [comment]
Low fidelity of landing page has been adapted from from wireframes
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A30339

**Comment by iruomavalerie** [comment]
All changes and reviews have been implemented
