### ISSUE TITLE
Low fidelity and high fidelity light mode of workspace

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#12]
Description: Design the low fidelity and  high fidelity light mode of workspace from sketches you made or got from suggested opinions putting in mind the laws of UX design

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned: Medina Folashade Sheriff

**Comment by medinasheriff** [comment]
Find below links to the screens I worked on on the project, consisting of 15 lofi pages and 15 hifi pages, bringing the total number to 30 desktop screens.

LOW FIDELITY DESIGNS
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A31085
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A37377
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A36973
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A37170
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A37525
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A31190
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A31878
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A31588
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A33584
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A33867
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A34150
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A33293
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A31389
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A32157
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A32157


HIGH FIDELITY DESIGNS
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=399%3A3315
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=839%3A19380
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=399%3A3464
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=839%3A19672
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=843%3A21780
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=850%3A22061
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A3832
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A3543
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A4110
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A4392
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A4674
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A6494
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A5161
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=917%3A21277
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=917%3A21957

**Comment by medinasheriff** [comment]
Link to high fidelity designs. All tasks completed and reviewed by team.
https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=43%3A486
