### ISSUE TITLE
Wire framing and Lo-fi design of account pages

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#13]
Description: Using the sketches you worked on and as agreed during meeting, design the wire-frames and low fidelity of account pages putting in mind, laws of UX design.

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned to: Uduije Calista

**Comment by Caly-design** [comment]
Work is ongoing on the account page....no issues, will send in feedback soon

**Comment by Caly-design** [comment]
Work completed... Please view it guys
https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=0%3A1

**Comment by Caly-design** [comment]
Links to Account frames, from frame 1-4, Hi-fi designs I worked on :
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=498%3A15584
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=498%3A16095
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1218%3A21526
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1218%3A21915
