### ISSUE TITLE
Low fidelity and High fidelity Light mode of workspace

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#14]
Description: Using the sketches agreed on by the "workspace team" following a specific pattern, design the low fidelity  and high fidelity light mode of workspace 

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned to: Ephraim Omenai

**Comment by omenaieph** [comment]
Done

**Comment by omenaieph** [comment]
Designed 15 pages each for the Workspace (Hi-fi and Lo-fi)
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=917%3A21957
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A5636
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A5921
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A6213
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A6784

**Comment by omenaieph** [comment]
Designed 15 pages each for the Workspace (Hi-fi and Lo-fi)

HiFi
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=917%3A21957
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A5636
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A5921
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A6213
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A6784
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A7463
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A7647
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A7837
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A8022
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=823%3A19533
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=824%3A19587
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=917%3A20620
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=917%3A20815
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A6882
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=418%3A7176
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=917%3A21040

LoFi
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A32432
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A32718
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A33011
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A34349
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A35030
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A37673
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A37854
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A38037
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A35204
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A35391
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A35573
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A34447
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A34742
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1383%3A36863
