### ISSUE TITLE
Wire framing and High fidelity dark mode of workspace 

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#16]
Description: Using sketches as agreed on during meeting design wire frames and high fidelity dark mode of workspace, keeping in mind the laws of UX design

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned to: Ekpubeni Avwerosuoghene Nature

**Comment by NatureReuben** [comment]
Complete ✅

**Comment by NatureReuben** [comment]
Wireframing design links for workspace I worked on:
16. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A2727
17. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=864%3A20699
18. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A3134
19. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A3428
20. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A3460
21. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A3182
22. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A3038
23. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A3278
24. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A3326
25. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=851%3A19951
26. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=358%3A2990

**Comment by NatureReuben** [comment]
High Fidelity design links for dark mode workspace I worked on:
16. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A7344
17. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A7629
18. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A7921
19. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A8492
20. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A9171
21. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A9355
22. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A9544
23. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A9728
24. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=917%3A20398
25. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=926%3A22911
26. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=917%3A22491
27. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=917%3A22702
28. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=438%3A8590
29. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=443%3A5350
30. https://www.figma.com/file/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?node-id=649%3A19263
