### ISSUE TITLE
High fidelity for landing page and community pages

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#21]
Description: Design high fidelity for both landing page and community pages observing all corrections made on the low fidelity during  team's scheduled meeting

**Comment by iruomavalerie** [comment]
Conversion to high fidelity from low fidelity has begun

**Comment by iruomavalerie** [comment]
Landing page light mode completed https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1507%3A21668

**Comment by iruomavalerie** [comment]
Community page light mode completed https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1178%3A24781

**Comment by iruomavalerie** [comment]
Landing page dark mode completed https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1507%3A22290

**Comment by iruomavalerie** [comment]
Community page dark mode completed https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=473%3A8729

**Comment by iruomavalerie** [comment]
All reviews and changes adapted
