### ISSUE TITLE
High fidelity dark mode of Account page

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#22]
Description: Design high fidelity dark mode of account page making necessary corrections as discussed at the previous scheduled meeting  prior to this assigned task obeying laws of UX design

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

**Comment by iruomavalerie** [comment]
Conversion from low fidelity to high fidelity design
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1178%3A26217

**Comment by Caly-design** [comment]
Thanks for commenting.... Task and updates completed as assigned review with the above link.
