### ISSUE TITLE
First Presentation Slide

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#23]
Description: Using figma, design beautiful and concise slides for the first presentation to Zuri-training for the work done so far as a team.

**Comment by hauwa003** [comment]
I worked together with @iruomavalerie to create the slides for the first presentation
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=1532%3A21625
