### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#24]
Do the prototyping of high fidelity of all the tasks completed so far. Play the prototype to have an overview of the design interactions with users, see to it that it is responsive.

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

**Comment by Cannon-Leo** [comment]
prototype completed link below

https://www.figma.com/proto/yzxxleZQG9HEVYpC3A1TSr/TEAM-110?page-id=1248%3A20145&node-id=1248%3A28769&viewport=1054%2C483%2C0.04&scaling=min-zoom&starting-point-node-id=1248%3A28769
