### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#6]
Description: As agreed upon from first meeting, design an appropriate complete style guides.

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned to: Hauwa Yusuf and Victoria Popoola

**Comment by vicady** [comment]
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=45%3A1199
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=644%3A8282
co-created the style guide for both the mobile app and the website.

**Comment by hauwa003** [comment]
Style guides for mobile and web created and adjusted by myself and @vicady 

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=644%3A8282
https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-(Copy)?node-id=45%3A1199
