### ISSUE TITLE
User Research plan

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#7]
Description: Create an effective user research plan as discussed during meeting.

Assigned to: Omoigberale Onyebuchi

**Comment by Cannon-Leo** [comment]
a. user research plan created here

https://docs.google.com/document/d/1Mv-0xBJvX8l-tcY9u_iq2AERaXqGLLfakH7fyUtju88/edit?usp=sharing

b. interview questions here

https://forms.gle/diuS8Sd69emkUrcq6

c. User research breakdown of user data and pain-poinst, persona, idea prioritization matrix and userflow plus the full user plan made with figjam here

https://www.figma.com/file/gU9iDjNYoZtHOvB8eOO5Gd/Compare-Wizard-User-Research?node-id=0%3A1

**Comment by Cannon-Leo** [comment]
a. user research plan created here

https://docs.google.com/document/d/1Mv-0xBJvX8l-tcY9u_iq2AERaXqGLLfakH7fyUtju88/edit?usp=sharing

b. interview questions here

https://forms.gle/diuS8Sd69emkUrcq6

c. User research breakdown of user data and pain-poinst, persona, idea prioritization matrix and userflow plus the full user plan made with figjam here

https://www.figma.com/file/gU9iDjNYoZtHOvB8eOO5Gd/Compare-Wizard-User-Research?node-id=0%3A1
