### ISSUE TITLE
User interview

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#8]
Description: Identify users on social media platforms or by any means. Using  already created User Research Plan, identify most preferred users (5-7) and then have a brief but concise interview with these users still using the User Research Plan with this singular aim, pinpointing their pain points.

Assigned to: Omoigberale Onyebuchi

**Comment by Cannon-Leo** [comment]
Using google meet, 5 users were interviewed

link to research plan with interview questions

https://docs.google.com/document/d/1Mv-0xBJvX8l-tcY9u_iq2AERaXqGLLfakH7fyUtju88/edit?usp=sharing

link to interview questions

https://forms.gle/diuS8Sd69emkUrcq6
