### ISSUE TITLE
Wire framing, lo-fi design and high fidelity of sign-up pages

### ISSUE THREAD

**Issue by Adepejuife** [zuri-training/Excel_comp_team_110#9]
Description: Using sketches as discussed during meeting, design wire-frames, low fidelity and high fidelity of sign-up pages putting in mind UX design laws

https://www.figma.com/file/ntOBzMvnmCOaNLEB12PHLg/TEAM-110-Copy

Assigned to: Tolulope Kresha

**Comment by tolulope-kresha** [comment]
The WiFi, LoFi and HiFi of the sign up pages have been completed by me and reviewed together as a team.
